sudo: required
dist: trusty
addons:
 apt:
  sources:
   - google-chrome
  packages:
   - google-chrome-stable
# latest version of firefox already installed by default
language: python
python:
 - 2.7
 - 3.5
 - 3.6
 - 3.7
env:
 - DISPLAY=:0.0
install:
 - npm install -g webdriver-manager
 - webdriver-manager update
 - pip install tox-travis
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - nohup webdriver-manager start --logging=ERROR &
 - sleep 10 # give webdriver some time to start
script:
 - export APPLITOOLS_BATCH_ID=`uuidgen -t`
 - echo $APPLITOOLS_BATCH_ID
 - tox
